matrix:
  include:
    - language: node_js
      node_js:
        - 14
      cache:
        directories:
          - node_modules
      before_install:
        - cd web
      env:
        CI: false
      script:
        - npm run build
        - npm test